# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cat Years' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cat Years
  pod 'Firebase/Core'
  pod 'Firebase/Storage'


  target 'Cat YearsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Cat YearsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
