# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ARNotebook' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ARNotebook
	pod 'Firebase/Core'
	pod 'Firebase/Database’
	pod 'Firebase/DynamicLinks'
	pod 'Firebase/Auth'
	pod ‘Firebase/Storage’
	pod 'FacebookCore'
	pod 'FacebookLogin'
end
